config/routes.rb
ProjectPlan::Application.routes.draw do
  resources :projects

  root :to => 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  def index
    @projects = Project.all
    Rails.logger.debug { "*** Returning all projects #{@projects.inspect}" }
  end
  
  def edit
    @project = Project.find(params[:id])
  end
  
  def update
    @project = Project.find(params[:id])
    @project.update_attributes(params[:project])
    redirect_to action: :index
  end

  def destroy
    Project.delete(params[:id])
    redirect_to action: :index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Example application for Winnipeg Ruby User Group to demo Page Objects pattern</title>
  <%= stylesheet_link_tag    "application" %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "application" %>
</head>
<body>
  <header class="navbar navbar-fixed">
    <div class="navbar-inner">
      <div class="container">
        <a class="brand" href="#">Demo Capybara</a>
        <ul class="nav">
          <li><%= link_to "Home", projects_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle='dropdown'>
              Projects
              <b class='caret'></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "List all projects", projects_path %></li>
              <li><%= link_to "New project", new_project_path %></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </header>
  <div class="container master-container">
    <ul class="breadcrumb">
      <%= yield :breadcrumb %>
    </ul>
    <div class='alert alert-info fade in' data-alert='alert'>
      <a class="close" data-dismiss='alert' href="#">×</a>
      <p>
        <strong>
          Demo at the <a href="http://devteach.com">Ruby Teach</a> about <a href="">Capybara</a>
        </strong>
      </p>
      <p>Here you will see how to use Capybara with Cucumber and rSpec<p>
    </div>

    <% if notice %>
      <div class="alert alert-success fade in" data-alert="alert">
        <a class="close" data-dismiss='alert' href="#">×</a>
        <p><%= notice %></p>
      </div>
    <% end %>

    <%= yield %>
  </div>
  <footer class="container">
    Copyright 2012 <a href="http://www.maventhought.com">MavenThought Inc.</a>
  </footer>
</body>
</html>

app/views/projects/edit.html.haml
- content_for :breadcrumb do
  %li
    =link_to "Home", projects_path 
    %span.divider /
  %li.active Edit project



= simple_form_for @project, :html => { :class => 'form-horizontal' }  do |f|

  %legend= @project.name
  
  = f.input :name, :input_html => { :class => "span6" }, :hint => "Project name"
                
  = f.input :active?, :as => :boolean 

  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = submit_tag 'Cancel', :type => :reset, :class => "btn btn-danger"

app/views/projects/index.html.haml
- content_for :breadcrumb do 
  %li.active Home


%h1 Listing Projects

- if @projects.empty?
  %h2 Projects are empty!

%table#projects{ class: "table table-bordered table-striped" }
  %thead
    %tr
      %th Name
      %th Description
      %th Active?
      %th Actions

  %tbody   
    - @projects.each do |p|
      %tr{"data-id" => p.id}
        %td= p.name
        %td= p.description
        %td= p.active?
        %td= link_to "Edit", edit_project_path(p)
        %td= link_to "Delete", project_path(p), :method => :delete, :class => "delete", :confirm => "Are you sure ?"